# Generated by Django 3.1.1 on 2020-10-25 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_auto_20201021_0158'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
