# Generated by Django 3.1.1 on 2020-11-19 19:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('name', models.CharField(default='', max_length=100)),
                ('phone', phone_field.models.PhoneField(blank=True, help_text='Phone number', max_length=31)),
                ('meetingURL', models.CharField(default='', max_length=100)),
                ('strengths', models.CharField(choices=[('--------', '--------'), ('Mathematics', 'Mathematics'), ('Chemistry', 'Chemistry'), ('Physics', 'Physics'), ('Computer Science', 'Computer Science'), ('Economics', 'Economics')], default='', max_length=255)),
                ('weaknesses', models.CharField(choices=[('--------', '--------'), ('Mathematics', 'Mathematics'), ('Chemistry', 'Chemistry'), ('Physics', 'Physics'), ('Computer Science', 'Computer Science'), ('Economics', 'Economics')], default='', max_length=255)),
                ('availability', models.CharField(choices=[('Monday Morning', 'Monday Morning'), ('Monday Afternoon', 'Monday Afternoon'), ('Tuesday Morning', 'Tuesday Morning'), ('Tuesday Afternoon', 'Tuesday Afternoon'), ('Wednesday Morning', 'Wednesday Morning'), ('Wednesday Afternoon', 'Wednesday Afternoon'), ('Thursday Morning', 'Thursday Morning'), ('Thursday Afternoon', 'Thursday Afternoon'), ('Friday Morning', 'Friday Morning'), ('Friday Afternoon', 'Friday Afternoon')], default='Monday Morning', max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
