# Generated by Django 3.1.1 on 2020-11-19 19:17

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('sbuddy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=phone_field.models.PhoneField(default='1234567890', help_text='Phone number', max_length=31),
        ),
    ]
