# Generated by Django 3.1.1 on 2020-11-19 20:03

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('sbuddy', '0002_auto_20201119_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(default='1234567890', help_text='Phone number', max_length=128, region=None),
        ),
    ]
