# Generated by Django 3.1.1 on 2020-11-08 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sbuddy', '0002_auto_20201108_0939'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='strengths',
            field=models.CharField(choices=[('--------', '--------'), ('Mathematics', 'Mathematics'), ('Chemistry', 'Chemistry'), ('Physics', 'Physics'), ('Computer Science', 'Computer Science'), ('Economics', 'Economics')], default='', max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='weakenesses',
            field=models.CharField(default='', max_length=255),
        ),
    ]
