# Generated by Django 3.1.1 on 2020-11-24 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sbuddy', '0003_remove_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='strengths',
            field=models.CharField(choices=[('--------', '--------'), ('Mathematics', 'Mathematics'), ('Chemistry', 'Chemistry'), ('Physics', 'Physics'), ('Computer Science', 'Computer Science'), ('Economics', 'Economics'), ('Engineering', 'Engineering'), ('Statistics', 'Statistics'), ('Psychology', 'Psychology'), ('Business', 'Business')], default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='weaknesses',
            field=models.CharField(choices=[('--------', '--------'), ('Mathematics', 'Mathematics'), ('Chemistry', 'Chemistry'), ('Physics', 'Physics'), ('Computer Science', 'Computer Science'), ('Economics', 'Economics'), ('Engineering', 'Engineering'), ('Statistics', 'Statistics'), ('Psychology', 'Psychology'), ('Business', 'Business')], default='', max_length=255),
        ),
    ]
