# Generated by Django 3.1.1 on 2020-11-08 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sbuddy', '0003_auto_20201108_1846'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='weakenesses',
            new_name='weaknesses',
        ),
    ]
