# Generated by Django 3.1.1 on 2020-11-08 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sbuddy', '0004_auto_20201108_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='weaknesses',
            field=models.CharField(choices=[('--------', '--------'), ('Mathematics', 'Mathematics'), ('Chemistry', 'Chemistry'), ('Physics', 'Physics'), ('Computer Science', 'Computer Science'), ('Economics', 'Economics')], default='', max_length=255),
        ),
    ]
