# Generated by Django 3.1.1 on 2020-11-10 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sbuddy', '0005_auto_20201108_1848'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.AddField(
            model_name='profile',
            name='availability',
            field=models.CharField(choices=[('1', 'Monday Morning'), ('2', 'Monday Afternoon'), ('3', 'Tuesday Morning'), ('4', 'Tuesday Afternoon'), ('5', 'Wednesday Morning'), ('6', 'Wednesday Afternoon'), ('7', 'Thursday Morning'), ('8', 'Thursday Afternoon'), ('9', 'Friday Morning'), ('10', 'Friday Afternoon')], default=1, max_length=2),
        ),
    ]
