# Generated by Django 3.1.1 on 2020-11-10 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sbuddy', '0007_auto_20201110_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='meetingURL',
            field=models.CharField(default='', max_length=100),
        ),
    ]
