# Generated by Django 3.1.3 on 2020-11-15 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sbuddy', '0008_profile_meetingurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(default='None', max_length=20),
        ),
    ]
